import { MongoClient } from 'mongodb';
import Head from 'next/head';
import Image from 'next/image';
import MeetupList from '../components/meetups/MeetupList';
import styles from '../styles/Home.module.css';

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meetups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MeetupList meetups={props.meetups} />

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// Static Render
export async function getStaticProps() {
  // Fetch data here
  const client = await MongoClient.connect(`mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASS}@cluster0.iyljx.mongodb.net/meetups?retryWrites=true&w=majority`);
  const db = client.db();
  const meetupsCollection = db.collection('meetups');
  const meetups = await meetupsCollection.find().toArray();

  client.close();

  return {
    props: {
      meetups: meetups.map((meetup) => ({
        title: meetup.title,
        address: meetup.address,
        image: meetup.image,
        id: meetup._id.toString(),
      })),
    },
    revalidate: 3600,
  };
}

// Server Render
// export async function getServerSideProps(context) {
//   const req = context.req;
//   const res = context.res;
//   // Fetch data here
//   return {
//     props: {
//       meetups: dummy_meetups,
//     }
//   }
// }
