import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import NewMeetupForm from '../../components/meetups/NewMeetupForm';

export default function NewMeetup() {
  const router = useRouter();

  async function addMeetupHandler(formData) {
    const response = await fetch('/api/new-meetup', {
      method: 'POST',
      body: JSON.stringify(formData),
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const data = await response.json();

    router.push('/');
  }

  return (
    <>
      <Head>
        <title>Add A New Meetup</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NewMeetupForm onAddMeetup={addMeetupHandler} />;
    </>
  );
}
